

version: '3'

services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant_reservation_database_dev
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
      MYSQL_INITDB_OPTS: --binary-mode
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    volumes:
      - test_vol:/var/lib/mysql
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-reservation-api
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/restaurant_reservation_database_dev
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: dev

volumes:
  test_vol:
