name: Java CI with Gradle

on:
  push:
    branches: [ "master", "tests" ] 
  pull_request:
    branches: [ "master", "develop" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2 # Updated to v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2 # Updated to v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle' # Added caching

    - name: Set execute permissions for Gradle Wrapper
      run: chmod +x ./gradlew # Added permissions for Gradle Wrapper

    - name: Build with Gradle Wrapper
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2 # Updated to v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2 # Updated to v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle' # Added caching

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0